### ISSUE TITLE
raspberry-mosquito-webserver-websocket-ESP8266

### ISSUE THREAD

**Issue by mkeyno** [bjosa/rpi-mosquitto#1]
sorry to open ticket to my question , but honestly I read many document across the web to find out how to make my raspberry pi as server to serve a webpage which is show status of any data came form external device , in this case I use ESP8266 deices to send data back to mosquito 1.4.11 which is installed on my raspberry . According to some resource , it is possible to run webserver by mosquito itself which is set by http_dir /usr/share/mosquitto/www config or could bind apache with websocket & MQTT , but none of the work for me , I really appreciated to have you tip or advice

**Comment by bjosa** [comment]
Sorry i have no experiences with setting up mosquitto as a web server. But as far as i know it's only possible to serve static data with the _http_dir_ option. So this will not fit for you. I would recommend to set up a little node.js app that also connects to the mqtt broker, read the data and deliver them via a http server. Just ask Google for [node.js](https://nodejs.org/en/), [express](http://expressjs.com/) (web framework for node.js) and mqtt.
You can find the documentation for the mosquitto configuration [here](https://mosquitto.org/man/mosquitto-conf-5.html).
